#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/alexgarneau/gSkinner/flutter/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/alexgarneau/gSkinner/flutter/flutter-wonders-app"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/alexgarneau/gSkinner/flutter/flutter-wonders-app/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=0.0.2"
export "FLUTTER_BUILD_NUMBER=0.0.2"
export "EXCLUDED_ARCHS=arm64"
export "DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/alexgarneau/gSkinner/flutter/flutter-wonders-app/.dart_tool/package_config.json"
