name: tests
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter test
#     - run: |
#         flutter config --enable-macos-desktop  
#         flutter test -d macos integration_test/smoke_test.dart
