name: tests
on: 
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  tests_self_hosted:
    runs-on: [self-hosted, macos]
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v2
    - run: flutter test
    - run: flutter test -d macos integration_test/smoke_test.dart
